### ISSUE TITLE
How can I contribute to Dutch video content ?

### ISSUE THREAD

**Issue by ngohungphuc** [kokimame/joytan#7]
Hi I want to send the Dutch course content in Duolingo but I'm only have the Dutch text 

I saw in this video https://youtu.be/FHg4A64B1-8 there is a sentence for German. Is there anyway to do this for Dutch course in Duolingo 

The content of Dutch vocalbulary can be found here https://paste.ofcode.org/teuTYCzWXUeuX5d54hLuZd

**Comment by kokimame** [comment]
Hi, @ngohungphuc . Sorry, I totally missed your issue for too long time. We discuss our YouTube-related stuff on our Slack. So please join our team from here (I'm more active there): http://slack-invite.joytan.pub/

Above all, I am very excited to work on any language. We will probably find someone who contributes native Dutch pronunciation via our Android app (in case you are not a Dutch speaker).  Open this issue if you have a further inquiry.
