### ISSUE TITLE
b'dyld: Library not loaded: /usr/local/Cellar/ffmpeg/3.3.2/lib/libavdevice.57.dylib\n  Referenced from: /Applications/Joytan.app/Contents/MacOS/ffmpeg\n  Reason: image not found\n''

### ISSUE THREAD

**Issue by ghost** [kokimame/joytan#8]
![issue](https://user-images.githubusercontent.com/63566211/101071142-cfd6e900-3561-11eb-82ca-fc984f822553.png)
I have that issue when I select the option "create audiobook", I don't no why, because already I have set up ffmpeg library, but this issue don't let me create an audiobook, please help. Thanks in advance

**Comment by ghost** [comment]
I already solved this issue, only by replacing the ffmpeg executable in the contents of the app with the ffmpeg executable I manually install by brew, searching in the finder I found the other exec. I hope this can be useful for someone had the same issue. Peace

**Comment by kokimame** [comment]
@TEN-byte Thanks. I did something really wrong for standalone executables accompanied with the app. Probably I should build ffmpeg, lame, or sox independently from my environment. Otherwise, I should clearly note that the manual installation of such programs is necessary.
